const initState = {
    vehicles:[
        {id:'1',name:'Tesla SUV',bags:'3',passengers:'7',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'},
        {id:'2',name:'Tesla SUV',bags:'4',passengers:'7',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'},
        {id:'3',name:'Tesla SUV',bags:'3',passengers:'8',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'},
        {id:'4',name:'Tesla SUV',bags:'3',passengers:'7',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'},
        {id:'5',name:'Tesla SUV',bags:'6',passengers:'10',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'},
        {id:'6',name:'Tesla SUV',bags:'3',passengers:'7',model:'Model X',rates:'1000/h',fuel:'Electric',availability:'available',description:'Model X is one of the safest SUVs ever. Built from the ground up as an electric vehicle, the body, chassis, restraints and battery technology provide a very low probability of occupant injury.',img:'https://images.unsplash.com/flagged/photo-1553505192-acca7d4509be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=767&q=80'}        
    ]
}

const vehicleReducer = (state = initState, action) => {
    return state;
}

export default vehicleReducer